#!/bin/sh

## BEGIN INIT INFO
# Provides:          appman
# Required-Start:    $network $syslog
# Required-Stop:     $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Author:            VladVons@gmail.com
# Short-Description: appman
# Description:       appman daemon
### END INIT INFO

NAME="appman_web"
DESCR="Some description $NAME"
PIDFILE="/var/run/$NAME.pid"
USER="www-data"

# Read default configuration variable
ENABLED=1
SCRYPT="AppMan_Web.py"
WORKDIR="/usr/share/$NAME"
DEFAULT="/etc/default/$NAME"
if [ -r $DEFAULT ] ; then
  . $DEFAULT
fi
DAEMON="$WORKDIR/$SCRYPT"

. /lib/lsb/init-functions

case "$1" in
  start)
    if [ $ENABLED = 1 ]; then
      log_daemon_msg "Starting $NAME "
      start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $USER  --chdir $WORKDIR --exec $DAEMON $ARGS
      log_end_msg $?
    else
      log_daemon_msg "Disabled by $DEFAULT"
    fi
    ;;
  stop)
    log_daemon_msg "Stopping $NAME "
    start-stop-daemon --stop --pidfile $PIDFILE --verbose
    log_end_msg $?
    ;;
  restart)
    $0 start
    $0 stop
    ;;
  status)
    log_action_msg "Status $DAEMON"
    status_of_proc -p $PIDFILE "$DAEMON"
    ;;
  *)
    echo $DESCR
    log_action_msg  "Usage: /etc/init.d/$NAME {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
